cc_binary(
  name = "pasta_main",
  srcs = ["pasta_main.cc"],
  deps = [
      "//data_handler:data_client",
      "//data_handler:data_handler",
      "//strategy:chase_momentum_strategy",
      "@absl//absl/status",
      "@com_github_google_glog//:glog",
  ],
)
